name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull rakshitgarg99126/toxic_comment_classifier:latest
    - name: Delete Old Docker container
      run: sudo docker rm -f toxic_comment_classifier-container || true
    - name: Run Docker container
      run: sudo docker run -d -p 8080:8080 --name toxic_comment_classifier-container rakshitgarg99126/toxic_comment_classifier
