name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log In to dockerHub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u DOCKERHUB_USERNAME -p DOCKERHUB_PASSWORD

    - name: Build docker image
      run: docker build -t toxic_comment_classifier .
    - name: Tag image docker
      run: docker tag toxic_comment_classifier:latest rakshitgarg99126/toxic_comment_classifier:latest
    - name: push docker image
      run: docker push rakshitgarg99126/toxic_comment_classifier:latest
